var RUN_TESTS = false;
var DEBUG = true;
var DELETE_WINDOW_CRYPTO = false;
var VERIFY_ENCRYPTION = false;
var ENCRYPTION_THREADS = 1;
var GENERATE_B64_IMAGES = false;	// re-generates lib/b64-images.js for verification
var CRYPTOSTORAGE_URL = "http://cryptostorage.com";	// TODO: change to https
var ONLINE_IMAGE_URL = CRYPTOSTORAGE_URL + "/favicon.ico";
var APP_DEPENDENCIES = ["lib/async.js", "lib/qrcode.js", "lib/jszip.js", "lib/crypto-js.js", "lib/bitaddress.js", "lib/progressbar.js", "lib/jquery.ddslick.js", "lib/b64-images.js", "lib/ua-parser.js"];
